# Generated by Django 5.0.2 on 2024-02-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_age_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_provider',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a provider.'),
        ),
    ]
