# Generated by Django 5.0.2 on 2024-02-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
