# Generated by Django 5.0.2 on 2024-02-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_socialplatform_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
