# Generated by Django 5.0.2 on 2024-03-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_notifications', to='accounts.notification'),
        ),
    ]
