# Generated by Django 5.0.2 on 2024-03-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_package_started_at_remove_package_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="1995-02-02T00:00:00Z"),
            preserve_default=False,
        ),
    ]
