# Generated by Django 5.0.2 on 2024-03-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_package_options_package_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_in_hand', models.BooleanField(default=False, help_text='Accepts cash in hand')),
                ('mcb_juice', models.BooleanField(default=False, help_text='Accepts MCB Juice payments')),
                ('internet_banking', models.BooleanField(default=False, help_text='Accepts internet banking payments')),
                ('card', models.BooleanField(default=False, help_text='Accepts card payments')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
