# Generated by Django 5.0.2 on 2024-03-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_card_paymentinformation_accepts_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
