# Generated by Django 5.0.2 on 2024-03-09 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_packagesubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesubscription',
            name='bookings_made',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
