# Generated by Django 5.0.2 on 2024-03-11 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_packagesubscription_bookings_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='number_of_bookings',
            field=models.IntegerField(blank=True, help_text='Number of bookings allowed', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
