# Generated by Django 5.0.2 on 2024-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gig',
            name='recurring_days',
            field=models.ManyToManyField(blank=True, related_name='gigs', to='gig.dayofweek'),
        ),
    ]
