# Generated by Django 5.0.2 on 2024-02-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0002_dayofweek_gig_date_gig_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='duration',
            field=models.PositiveIntegerField(default=90),
            preserve_default=False,
        ),
    ]
