# Generated by Django 5.0.2 on 2024-02-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0003_gig_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
