# Generated by Django 5.0.2 on 2024-02-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0004_gig_end_time_gig_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='duration',
        ),
    ]
