# Generated by Django 5.0.2 on 2024-02-21 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0005_remove_gig_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='gig.gig')),
            ],
            options={
                'unique_together': {('gig', 'date', 'start_time')},
            },
        ),
    ]
