# Generated by Django 5.0.2 on 2024-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0006_giginstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='giginstance',
            name='bookings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
