# Generated by Django 5.0.2 on 2024-02-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0007_giginstance_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
