# Generated by Django 5.0.2 on 2024-02-23 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0011_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs', to='gig.category'),
        ),
    ]
