# Generated by Django 5.0.2 on 2024-02-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0012_alter_gig_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='giginstance',
            name='max_people',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
