# Generated by Django 5.0.2 on 2024-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0015_giginstance_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
