# Generated by Django 5.0.2 on 2024-03-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0017_gig_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
