# Generated by Django 5.0.2 on 2024-03-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_packagesubscription_status'),
        ('gig', '0019_booking_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.packagesubscription'),
        ),
    ]
