# Generated by Django 5.0.2 on 2024-03-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0020_booking_package_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='package_unapplicable',
            field=models.BooleanField(default=False),
        ),
    ]
